### PR TITLE
Fixes #43

### LINKED ISSUE #43: New stroke should default to `none`
`stroke: currentColor` affects the weight of the icon. See the clock example with `stroke: currentColor`:

screen shot 2015-10-19 at 5 03 18 pm

`stroke: none` preserves 1.0.5's look:

screen shot 2015-10-19 at 5 03 34 pm

### PR DESCRIPTION
**Pull request by ebidel**
R: @notwaldorf

### CODE REVIEW

**Comment by ebidel** [comment]
Shall we retag 1.0.6 after this is merged?

**Comment by notwaldorf** [comment]
@ebidel I can just tag 1.0.7. Numbers have no meanings :)

**Comment by notwaldorf** [comment]
Oh, i see. Yeah, good catch, thanks!

**Comment by ebidel** [comment]
Fair enough. Keep em coming!

**Pull request merged**
