### PR TITLE
Move <template> to _template

### PR DESCRIPTION
**Pull request by Punk-UnDeaD**

### CODE REVIEW

**Comment by Punk-UnDeaD** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Closing this, as this is a non-standard way to write an element. What is this PR trying to fix?

**Comment by Punk-UnDeaD** [comment]
If this is done and application builded to one js file, firefox has badass improve performance

**Comment by Punk-UnDeaD** [comment]
Do you hate Firefox users and web-depelopers so much that you think that they should suffer for the sake of the standart?

**Comment by notwaldorf** [comment]
I've already answered and closed this in #113. Please see that thread for the complete answer

**Comment by Punk-UnDeaD** [comment]
`Saving the template as a string this way has absolutely no performance implications, despite what you might think. From the string, you still have to construct the DOM if you want to stamp it, which Polymer automatically does (when it fetches the template from the <template> tag)`

building app to one js and link it as script without defered parsing improve performance in firefox from zero to infynity 
for this we need move all templates for all components to script, build it and extract pure js
pls,  beleave me or try it

do you want work on performance or hate firefox users?

**Comment by dfreedm** [comment]
I'd really like to see some citations for "improve performance in firefox from zero to infynity".
However, what you've done so far is break the 1.x tests because `_template` does not support strings in Polymer 1.

Until such time as you can clearly show a performance benefit without breaking the tests, we cannot accept this pull request, nor any similar ones.

**Comment by Punk-UnDeaD** [comment]
https://github.com/Punk-UnDeaD/polypoly
pls, check examples from this repo
I use paper-progress, but I can add iron-icon too
vanilla folder has polymer components builded by `polymer build`
patched folder has patched component builded as js
pls open index-compressed.html from both folder in firefox and you can see difference without stopwatch

**Pull request closed without merging**
