### PR TITLE
Use display inline-block to 1) Fix icon size on safari 2) Match 0.5

### LINKED ISSUE #3: Safari: setting CSS width or height does nothing to set the size of the icon
http://jsbin.com/noxaju/3/edit

Chrome (above) vs Safar (below)
screen shot 2015-04-19 at 1 34 23 pm

The icon unexpectedly (and differs from 0.5 behavior) takes the size of the nearest positioned parent (as per regular CSS rules)

### PR DESCRIPTION
**Pull request by peterwmwong**
Fixes #3

### CODE REVIEW

**Comment by cdata** [comment]
I'm curious: what is the issue in Safari (version?)?

**Comment by peterwmwong** [comment]
@cdata please see Issue #3 (screenshot and jsbins)

**Comment by peterwmwong** [comment]
Fixed by #6

**Pull request closed without merging**
