### PR TITLE
feat(iron-icon.html): add an open mixin to :host

### PR DESCRIPTION
**Pull request by carolirod**
Maybe would fix issue #47 ?
(apart that I need to add a transform rotate myself through this mixin)

Thanks!

### CODE REVIEW

**Comment by JosefJezek** [comment]
Please merge this mixin...

**Comment by carolirod** [comment]
just updated the branch so it has no conflicts

**Comment by notwaldorf** [comment]
@carolirod Would you mind documenting this in the `Styling` section, please?

**Comment by carolirod** [comment]
Sure, (I did forget) there you go

**Comment by notwaldorf** [comment]
Thanks!

**Pull request merged**
